[project]
name = "cfts"
description = "Paradigms for running auditory function tests using psiexperiment"
requires-python = ">=3.10"
license = {file = "LICENSE.txt"}
authors = [
    {name = "Brad Buran", email="buran@ohsu.edu"},
]
maintainers = [
    {name = "Brad Buran", email="buran@ohsu.edu"},
]
dependencies = [
    "cftscal",
    "cftsdata >=0.1.8",
    "psiexperiment[zarr]",
	"psiapp >= 0.0.3",
    "enaml >=0.19.0",
    "tqdm",
]
dynamic = ["version"]

[project.optional-dependencies]
ni = ["psiexperiment[ni]"]
tdt = ["psiexperiment[tdt]"]
docs = ["sphinx", "sphinx_rtd_theme", "pygments-enaml"]
test = ["pytest", "pytest-console-scripts", "matplotlib"] # Matplotlib is used in some of the validation scripts.
dev = ["coloredlogs"]

[project.scripts]
cfts = "cfts.app.main:cfts"

[build-system]
requires = ["setuptools>=61.2", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "cfts/version.py"
